parameters:
#    dev_skills.example.class: Dev\SkillsBundle\Example

services:
#    dev_skills.example:
#        class: %dev_skills.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
